#if !canImport(ObjectiveC)
import XCTest

extension LicensedComponentTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LicensedComponentTests = [
        ("testBundledLicences", testBundledLicences),
        ("testCreation", testCreation),
        ("testCustomLicense", testCustomLicense),
        ("testDynamicPropertyConformance", testDynamicPropertyConformance),
        ("testHashableConformance", testHashableConformance),
        ("testIdentifiableConformance", testIdentifiableConformance),
        ("testTextResolving", testTextResolving),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(LicensedComponentTests.__allTests__LicensedComponentTests),
    ]
}
#endif
